// ITableLogs
export const SET_TABLE_DATA_LOG = "SET_TABLE_DATA_LOG";
export type SET_TABLE_DATA_LOG = typeof SET_TABLE_DATA_LOG;

export const SET_TABLE_HEADER_LOG = "SET_TABLE_HEADER_LOG";
export type SET_TABLE_HEADER_LOG = typeof SET_TABLE_HEADER_LOG;

export const DELETE_TABLE_SESSION = "DELETE_TABLE_SESSION";
export type DELETE_TABLE_SESSION = typeof DELETE_TABLE_SESSION;

// IGraphLogs
export const SET_GRAPH_LOGS = "SET_GRAPH_LOGS";
export type SET_GRAPH_LOGS = typeof SET_GRAPH_LOGS;
export const DELETE_GRAPH_SESSION = "DELETE_GRAPH_SESSION";
export type DELETE_GRAPH_SESSION = typeof DELETE_GRAPH_SESSION;
